#!/bin/bash

NAMESPACE=$1
COMMAND=$2
RESOURCE_TYPE=$3

echo "Resource,Namespace,Name,CPU,Memory"

kubectl "$COMMAND" "$RESOURCE_TYPE" -n "$NAMESPACE" | tail -n +2 | while read -r line
do
  NAME=$(awk '{print $1}' <<< "$line")

  if [[ "$RESOURCE_TYPE" == "nodes" ]]; then
    CPU=$(awk '{print $2}' <<< "$line")
    MEMORY=$(awk '{print $4}' <<< "$line")
  else
    CPU=$(awk '{print $2}' <<< "$line")
    MEMORY=$(awk '{print $3}' <<< "$line")
  fi

  echo "$RESOURCE_TYPE,$NAMESPACE,$NAME,$CPU,$MEMORY"
done | column -t -s ","